name: Build & Test Docker Image

on:
  # runs autonomously upon regular push
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  # can be invoked by publish job
  workflow_call:
  # can be triggered manually
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # set up build tools
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # build image with local caching
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          tags: chgio/python4capella-docker:latest
          load: true
          cache-to: type=local,dest=/tmp/docker-cache
      # run image test script in container, relaying exit code
      # (test fails => step fails => job fails)
      - name: Test image
        run: |
          xvfb-run -s "-screen 0 1280x720x24" \
            capella -nosplash \
            -application org.polarsys.capella.core.commandline.core \
            -appid org.eclipse.python4capella.commandline \
            -data /opt/capella-${CAPELLA_VER}/workspace \
            -import "/opt/capella-${CAPELLA_VER}/Python4Capella|/workspace/sample/models/In-Flight Entertainment System" \
            "/workspace/sample/scripts/Python4Capella-Scripts/List_logical_components_in_console.py" "/workspace/sample/models/In-Flight Entertainment System/In-Flight Entertainment System.aird" \
            > /tmp/out.txt
          grep "In-Flight Entertainment System
            - IFE System
            - Passenger
            - Cabin Crew
            - Aircraft
            - Ground Operator" \
            /tmp/out.txt
          exit $?
      # upload Docker build cache for publish job
      - name: Upload cache as artifact
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/upload-artifact@v4
        with:
          name: Docker Cache
          path: /tmp/docker-cache
