name: Publish Docker Image & Create Release

on:
  # runs autonomously upon version tag push
  push:
    tags:
      - 'v*'

jobs:
  # list build-test job for reuse
  build-test:
    uses: ./.github/workflows/build-test.yml

  publish:
    # invoke build-test job
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      # authenticate
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # download Docker build cache from build-test job
      - name: Download cache as artifact
        uses: actions/download-artifact@v4
        with:
          name: Docker Cache
          path: /tmp
      # publish image from cache
      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          tags: chgio/python4capella-docker:latest,chgio/python4capella-docker:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/docker-cache
          push: true

  release:
    # invoke build-test job
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      # create draft release
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
