name: Publish Docker Image & Create Release

on:
  # runs autonomously upon pushing any tag
  push:
    tags:
      - '*'

jobs:
  # list build-test job for reuse
  build-test:
    uses: ./.github/workflows/build-test.yml

  publish:
    # invoke build-test job
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      # authenticate
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # download Docker imgspec tarball from build-test job
      - name: Download image as artifact
        uses: actions/download-artifact@v4
        with:
          name: Docker Image (TAR)
          path: /tmp
      # load Docker imgspec tarball
      - name: Load image
        run: docker load --input /tmp/python4capella-docker-image.tar
      # tag latest image with version number
      - name: Tag image
        run: docker tag chgio/python4capella-docker:latest chgio/python4capella-docker:${{ github.ref_name }}
      # push image with all tags
      - name: Push image
        run: docker push --all-tags chgio/python4capella-docker

  release:
    # invoke build-test job
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      # create draft release
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
